# Generated by Django 4.1.3 on 2023-06-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_appointment_table_alter_doctor_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admint',
        ),
        migrations.DeleteModel(
            name='Testresult',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientdischargedetails',
            options={},
        ),
        migrations.DeleteModel(
            name='Treats',
        ),
    ]
