# Generated by Django 4.1.3 on 2023-06-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0021_delete_admint_delete_testresult_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="appointment", table=None,),
        migrations.AlterModelTable(name="doctor", table=None,),
        migrations.AlterModelTable(name="patient", table=None,),
        migrations.AlterModelTable(name="patientdischargedetails", table=None,),
    ]
