# Generated by Django 4.1.3 on 2023-06-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_admint_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
